import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {createWriteStream} from 'node:fs';
import {ZipArchive} from 'archiver';
import {Storage,safePath} from '../server/storage.js';
import {importPackage,extractZip} from '../server/import.js';
async function fixture(){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'handoff-import-'));const store=new Storage(path.join(dir,'data'));await store.init();return {dir,store};}
async function zip(dir:string,files:Record<string,string>){const file=path.join(dir,`input-${Math.random()}.zip`);const stream=createWriteStream(file);const done=new Promise<void>((r,j)=>{stream.on('close',r);stream.on('error',j);});const a=new ZipArchive({zlib:{level:9}});a.pipe(stream);for(const [name,content]of Object.entries(files))a.append(content,{name});await a.finalize();await done;return file;}
const html='<!doctype html><html><head><link rel="stylesheet" href="assets/main.css"></head><body><img src="assets/photo.svg"><script src="app.js"></script></body></html>';
const files={'project/standalone.html':html,'project/assets/main.css':'body{color:red}','project/assets/photo.svg':'<svg xmlns="http://www.w3.org/2000/svg"/>','project/app.js':'console.log("test")'};
test('legacy nested project import, relative assets and byte-exact archived original survive restart',async()=>{const {dir,store}=await fixture();const archive=await zip(dir,files);const v=await importPackage(store,archive,{name:'测试',label:'v1'});assert.equal(v.previewRoot,'project');assert.equal(v.pages[0].path,'standalone.html');assert.equal(v.workflowStatus,'reviewing');assert.deepEqual(await fs.readFile(archive),await fs.readFile(path.join(store.directory(v.id),'package.zip')));const restart=new Storage(store.root);await restart.init();assert.equal(restart.version(v.id).label,'v1');});
test('manifest page states and source archive are version-bound; duplicate version rejected',async()=>{const {dir,store}=await fixture();const manifest={schemaVersion:1,name:'活动',version:'v1',previewRoot:'.',sourceArchive:'source.zip',pages:[{id:'home',name:'首页',path:'standalone.html',width:402,height:903},{id:'rank',name:'榜单',path:'standalone.html#rank',width:402,height:1367}]};const archive=await zip(dir,{...files,'project/handoff.json':JSON.stringify(manifest),'project/source.zip':'example archive'});const v=await importPackage(store,archive,{});assert.equal(v.pages.length,2);assert.equal(v.sourceArchive,'project/source.zip');await assert.rejects(importPackage(store,archive,{projectId:v.projectId}),/版本号已存在/);const next=await importPackage(store,archive,{projectId:v.projectId,label:'v2'});assert.equal(next.projectId,v.projectId);assert.equal(next.workflowStatus,'ready');assert.notEqual(next.id,v.id);assert.equal(store.state.projects.length,1);assert.equal(store.state.versions.length,2);});
test('missing resources and unbuilt React source are rejected before publishing',async()=>{const {dir,store}=await fixture();await assert.rejects(importPackage(store,await zip(dir,{'index.html':html}),{}),/缺少预览资源/);await assert.rejects(importPackage(store,await zip(dir,{'index.html':'<script src="/src/main.tsx"></script>'}),{}),/未构建/);assert.equal(store.state.versions.length,0);});
test('unsafe paths, environment files and root-relative Vite assets rejected',async()=>{const {dir,store}=await fixture();assert.throws(()=>safePath(dir,'../escape'),/越界/);assert.throws(()=>safePath(dir,'a\\escape'),/越界/);await assert.rejects(importPackage(store,await zip(dir,{'index.html':'ok','.env.production':'private'}),{}),/环境配置/);await assert.rejects(importPackage(store,await zip(dir,{'index.html':'<script src="/assets/app.js"></script>','assets/app.js':'ok'}),{}),/根路径/);});
test('manifest traversal, duplicate state IDs and invalid design links rejected',async()=>{const {dir,store}=await fixture();const manifest={schemaVersion:1,name:'Test',version:'v1',previewRoot:'../',pages:[{id:'home',name:'首页',path:'index.html',width:402,height:903}]};await assert.rejects(importPackage(store,await zip(dir,{'handoff.json':JSON.stringify(manifest),'index.html':'ok'}),{}),/越界/);manifest.previewRoot='.';manifest.pages.push(manifest.pages[0]);await assert.rejects(importPackage(store,await zip(dir,{'handoff.json':JSON.stringify(manifest),'index.html':'ok'}),{}),/ID 不能重复/);});
test('serialized storage updates preserve concurrency; failed mutations do not poison future writes',async()=>{const {store}=await fixture();await Promise.all(Array.from({length:8},(_,i)=>store.update(s=>s.projects.push({id:String(i),name:String(i),figmaUrl:'',createdAt:''}))));assert.equal(store.state.projects.length,8);await assert.rejects(store.update(()=>{throw Error('intentional');}));await store.update(s=>{s.projects[0].name='updated';});assert.equal(store.state.projects[0].name,'updated');});
test('invalid and duplicate ZIP entries fail with no published version',async()=>{const {dir,store}=await fixture();const bad=path.join(dir,'bad.zip');await fs.writeFile(bad,'not zip');await assert.rejects(importPackage(store,bad,{}),/ZIP/);assert.equal(store.state.versions.length,0);});
